In [1]:
import numpy as np

# 行列AとBを定義
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

# 行列の積を計算
C = np.dot(A, B)

# 結果を表示
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix A x B:")
print(C)

# 計算された行列の要素の最大値を求めて表示
max_value = np.max(C)
print("\nMaximum value in the resulting matrix:")
print(max_value)


Matrix A:
[[0 1]
 [2 3]
 [4 5]]

Matrix B:
[[0 1 2 3]
 [4 5 6 7]]

Matrix A x B:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

Maximum value in the resulting matrix:
47
